config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :stores

  root 'stores#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :services do
    resources :stores, only: [:index] do

    end
    get 'articles' => '/services/articles#index'
    get 'articles/stores/:id' => '/services/articles#by_store'
  end

  get "/404" => "errors#not_found", :as => :not_found
  get "/500" => "errors#exception", :as => :error
  get "/400" => "errors#bad_request", :as => :bad_request
  get '*not_found', to: 'errors#not_found'

end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :store
  validates :name, presence: true
  validates :price, presence: true, numericality: true
  validates :total_in_shelf, presence: true, numericality: true
  validates :total_in_vault, presence: true, numericality: true

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, :description, :price, :total_in_shelf, :total_in_vault, :store_id)
    end
end

app/controllers/services/articles_controller.rb
class Services::ArticlesController < Services::ApiController

  def index
    @articles = ::Article.all

    respond_to do |format|

      format.json {
        render json: {
          articles: ActiveModel::Serializer::CollectionSerializer.new(@articles, each_serializer: ArticleSerializer),
          success: true,
          total_elements: @articles.count
        },
        status: 200
      }

      format.xml {
        render xml: {
          articles: @articles,
          success: true,
          total_elements: @articles.count
        }.to_xml(root: 'articles'),
        except: [:created_at, :updated_at],
        status: 200
      }
    end
  end

  def by_store

    if /\d+/=~ params[:id]
      begin
        store = ::Store.find(params[:id])
        @articles = ::Article.where(store: store)

        respond_to do |format|

          format.json {
            render json: {
              articles: ActiveModel::Serializer::CollectionSerializer.new(@articles, each_serializer: ArticleSerializer),
              success: true,
              total_elements: @articles.count
            },
            status: 200
          }

          format.xml {
            render xml: {
              articles: @articles,
              success: true,
              total_elements: @articles.count
            }.to_xml(root: 'articles'),
            except: [:created_at, :updated_at],
            status: 200
          }
        end

      rescue ActiveRecord::RecordNotFound
        respond_to do |format|
          format.json {
            render json: {
              error_msg:  'Record Not Found',
              error_code: 404,
              success:    false
            },
            status: 404
          }

          format.xml {
            render xml: {
              error_msg:  'Record Not Found',
              error_code: 404,
              success:    false
            }.to_xml(root: 'error'),
            except: [:created_at, :updated_at],
            status: 404
          }
        end
      end
    else
      respond_to do |format|
        format.json {
          render json: {
            error_msg:  'Bad request',
            error_code: 400,
            success:    false
          },
          status: 400
        }

        format.xml {
          render xml: {
            error_msg:  'Bad request',
            error_code: 400,
            success:    false
          }.to_xml(root: 'error'),
          status: 400
        }
      end
    end

  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.haml
= form_for @article do |f|
  .row
    .col.s12
      - if @article.errors.any?
        .card.red.darken-1
          .card-content.white-text
            %h4= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
            %ul
              - @article.errors.full_messages.each do |msg|
                %li= msg

      .field
        = f.label :name
        = f.text_field :name
      .field
        = f.label :description
        = f.text_area :description, class: "materialize-textarea"
      .field
        = f.label :price
        = f.text_field :price
      .field
        = f.label :total_in_shelf
        = f.number_field :total_in_shelf
      .field
        = f.label :total_in_vault
        = f.number_field :total_in_vault
      .field
        = f.label :store
        = f.select :store_id, options_for_select(Store.all.map{|s|[s.name, s.id]}), {}, {class: 'browser-default'}
      .actions
        = f.submit t('article.save'), class: "waves-effect waves-light btn"
        = link_to  t('article.back'), articles_path, class: "grey darken-4 waves-effect waves-light btn"

app/views/articles/edit.html.haml
%h2
  = t('article.editing', name: @article.name)

= render 'form'

= link_to t('article.show'), @article
\|
= link_to t('article.index'), articles_path

app/views/articles/index.html.haml
%h2
  = t('article.index')

%table.bordered.responsive-table
  %thead
    %tr
      %th
        = t('article.fields.name')
      %th
        = t('article.fields.description')
      %th
        = t('article.fields.price')
      %th
        = t('article.fields.total_in_shelf')
      %th
        = t('article.fields.total_in_vault')
      %th
        = t('article.fields.store')
      %th
      %th
      %th

  %tbody
    - @articles.each do |article|
      %tr
        %td= article.name
        %td= article.description
        %td= article.price
        %td= article.total_in_shelf
        %td= article.total_in_vault
        %td= article.store.name
        %td
          %i.tiny.material-icons
            visibility
          = link_to t('article.show'), article
        %td
          %i.tiny.material-icons
            mode_edit
          = link_to t('article.edit'), edit_article_path(article)
        %td
          %i.tiny.material-icons
            delete
          = link_to t('article.delete'), article, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to t('article.new'), new_article_path, class: "waves-effect waves-light btn"

app/views/articles/new.html.haml
.row
  .col.s12
    %h2
      = t('article.new')

.row
  .col.s12
    = render 'form'

app/views/articles/show.html.haml
%h2
  = @article.name

%p#notice= notice

%p
  %b
    = "#{t('article.fields.name')}:"
  = @article.name
%p
  %b
    = "#{t('article.fields.description')}:"
  = @article.description
%p
  %b
    = "#{t('article.fields.price')}:"
  = @article.price
%p
  %b
    = "#{t('article.fields.total_in_shelf')}:"
  = @article.total_in_shelf
%p
  %b
    = "#{t('article.fields.total_in_vault')}:"
  = @article.total_in_vault
%p
  %b
    = "#{t('article.fields.store')}:"
  = @article.store.name

= link_to t('article.edit'), edit_article_path(@article)
\|
= link_to t('article.index'), articles_path