config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :stores

  root 'stores#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :services do
    resources :stores, only: [:index] do

    end
    get 'articles' => '/services/articles#index'
    get 'articles/stores/:id' => '/services/articles#by_store'
  end

  get "/404" => "errors#not_found", :as => :not_found
  get "/500" => "errors#exception", :as => :error
  get "/400" => "errors#bad_request", :as => :bad_request
  get '*not_found', to: 'errors#not_found'

end

app/models/store.rb
class Store < ApplicationRecord
  validates :name, presence: true
  validates  :address, presence: true
  
  has_many :articles
end

app/controllers/services/stores_controller.rb
class Services::StoresController < Services::ApiController

  def index
    @stores = ::Store.all

    respond_to do |format|

      format.json {
        render json: {
          stores: ActiveModel::Serializer::CollectionSerializer.new(@stores, each_serializer: StoreSerializer),
          success: true,
          total_elements: @stores.count
        },
        status: 200
      }

      format.xml {
        render xml: {
          stores: @stores,
          success: true,
          total_elements: @stores.count
        }.to_xml(root: 'stores'),
        except: [:created_at, :updated_at],
        status: 200
      }
    end
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :address)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.haml
= form_for @store do |f|
  .row
    .col.s12
      - if @store.errors.any?
        .card.red.darken-1
          .card-content.white-text
            %h4= "#{pluralize(@store.errors.count, "error")} prohibited this store from being saved:"
            %ul
              - @store.errors.full_messages.each do |msg|
                %li= msg

      .field
        = f.label :name
        = f.text_field :name
      .field
        = f.label :address
        = f.text_field :address
      .actions
        = f.submit t('store.save'), class: "waves-effect waves-light btn"
        = link_to t('store.back'), stores_path, class: "grey darken-4 waves-effect waves-light btn"

app/views/stores/edit.html.haml
%h2
  = t('store.editing', name: @store.name)

= render 'form'

= link_to t('store.show'), @store
\|
= link_to t('store.index'), stores_path

app/views/stores/index.html.haml
%h2
  = t('store.index')

%table.bordered.responsive-table
  %thead
    %tr
      %th
        = t('store.fields.name')
      %th
        = t('store.fields.address')
      %th
      %th
      %th

  %tbody
    - @stores.each do |store|
      %tr
        %td= store.name
        %td= store.address
        %td
          %i.tiny.material-icons
            visibility
          = link_to t('store.show'), store
        %td
          %i.tiny.material-icons
            mode_edit
          = link_to t('store.edit'), edit_store_path(store)
        %td
          %i.tiny.material-icons
            delete
          = link_to t('store.delete'), store, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to t('store.new'), new_store_path, class: "waves-effect waves-light btn"

app/views/stores/new.html.haml
.row
  .col.s12
    %h2
      = t('store.new')

.row
  .col.s12
    = render 'form'

app/views/stores/show.html.haml
%h2
  = @store.name

%p#notice= notice

%p
  %b
    = "#{t('store.fields.name')}:"
  = @store.name
%p
  %b
    = "#{t('store.fields.address')}:"
  = @store.address

= link_to t('store.edit'), edit_store_path(@store)
\|
= link_to t('store.index'), stores_path